version: "3.8"
services:
  postgres: 
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=dat
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cine-deep-match
    ports: 
      - "5432:5432"
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://dat:secret@postgres:5432/cine-deep-match?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]
    
